myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.contrib import admin

from  index.views import IndexView

urlpatterns = [
    path('',IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
]

myproject/index/models.py
from django.db import models
import datetime
import  django.utils.timezone as timezone
# Create your models here.
class Project(models.Model):
    STATUS_ITEMS=[
        (0,'申请'),
        (1,'进行'),
        (2,'归档'),
        (3,'作废')
    ]
    PROJECT_TYPES=[
        (0,'安全检查'),
        (1,'风险评估'),
        (2,'等保测评'),
        (3,'定额造价')
    ]
    name = models.CharField(max_length=128, verbose_name="项目名称")
    types = models.IntegerField(choices=PROJECT_TYPES,default=0,verbose_name="项目分类")
    create_time=models.DateField(auto_now_add=True,editable=False,verbose_name="创建时间")
    start_time=models.DateField(verbose_name="开始时间",null=True,blank=True)
    close_time=models.DateField(verbose_name="结束时间",null=True)
    status=models.IntegerField(choices=STATUS_ITEMS,default=0, verbose_name="项目状态")
    def __str__(self):
        return '<项目:{}>'.format(self.name)

    @classmethod
    def get_all(cls):
        return cls.objects.all()

    class Meta:
        verbose_name=verbose_name_plural="项目信息"

myproject/index/forms.py
from django import forms
from .models import  Project

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = (
            'name','types',
            'start_time','close_time',
            'status'
        )

myproject/index/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.shortcuts import render

from .models import Project
from .forms import ProjectForm
from django.http import HttpResponseRedirect
from django.shortcuts import  render
from django.urls import reverse
from django.views import View

from .forms import  ProjectForm
from .models import  Project

# Create your views here.
class IndexView(View):
    template_name='index.html'

    def get_context(self):
        projects= Project.get_all()
        context = {
            'projects':projects
        }
        return  context

    def get(self,request):
        context = self.get_context()
        form = ProjectForm()
        context.update({
            'form':form
        })
        return render(request, self.template_name, context=context)

    def post(self,request):
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('index'))
        context = self.get_context()
        context.update({
            'form':form
        })
        return render(request, self.template_name, context=context)

myproject/index/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>项目文件管理系统</title>
    </head>
    <body>
        <h3><a href="/admin/">Admin</a>></h3>

        <ul>
            <table border="1" cellpadding="0">
                
                <tr>
                    <td>项目名称</td>
                    <td>项目分类</td>
                    <td>创建时间</td>
                    <td>项目状态</td>
                    <td>操作</td>
                </tr>

            {% for project in projects %}

            <tr>
                <td>{{project.name}} </td>
                <td>{{project.get_types_display}}</td>
                <td>{{project.create_time}}</td>
                <td>{{project.get_status_display}}</td>
                <td>
                     <a href="/edit_user-{{ project.id }}/">编辑</a>
                     <a href="/del_user-{{ project.id }}/">删除</a>

                </td>
            </tr>
            {% endfor %}
            </table>
        </ul>
        <hr/>
        <form action="/" method="post">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Submit" />
        </form>
    </body>
</html>